<?php

namespace AppBundle\Repository;

/**
 * RepoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retrieve all repositories to be fetched for new release.
     *
     * @return array
     */
    public function findAllForRelease()
    {
        $data = $this->createQueryBuilder('r')
            ->select('r.id')
            ->getQuery()
            ->getArrayResult();

        $return = [];
        foreach ($data as $oneData) {
            $return[] = $oneData['id'];
        }

        return $return;
    }

    /**
     * Count total repos.
     *
     * @return int
     */
    public function count()
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r.id) as total')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
