<?php

namespace AppBundle\Repository;

/**
 * StarRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarRepository extends \Doctrine\ORM\EntityRepository
{
}
