<?php

namespace AppBundle\Repository;

/**
 * VersionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all versions available for the given user.
     * They'll be put in a RSS feed.
     *
     * @param  int $userId
     *
     * @return array
     */
    public function findForUser($userId)
    {
        return $this->createQueryBuilder('v')
            ->select('v.id', 'v.tagName', 'v.createdAt', 'v.body', 'r.fullName', 'r.ownerAvatar')
            ->leftJoin('v.repo', 'r')
            ->leftJoin('r.stars', 's')
            ->leftJoin('s.user', 'u')
            ->where('s.user = ' . $userId)
            ->andWhere('v.createdAt >= u.createdAt')
            ->orderBy('v.createdAt', 'desc')
            ->setMaxResults(10)
            ->getQuery()
            ->getArrayResult();
    }
}
